### ISSUE TITLE
REST API cannot retrieve large clades

### ISSUE THREAD

**Issue by ethanbass** [DessimozLab/pyomadb#1]
Working up the tree from Homininae:

```
import omadb

# these requests work fine
dendropy_tree = c.taxonomy.dendropy_tree(root='Homininae')
dendropy_tree = c.taxonomy.dendropy_tree(root='Homininae')
dendropy_tree = c.taxonomy.dendropy_tree(root='Hominidae')
dendropy_tree = c.taxonomy.dendropy_tree(root='Hominoidea')
dendropy_tree = c.taxonomy.dendropy_tree(root='Catarrhini')
dendropy_tree = c.taxonomy.dendropy_tree(root='Simiiformes')
dendropy_tree = c.taxonomy.dendropy_tree(root='Primates')
dendropy_tree = c.taxonomy.dendropy_tree(root='Euarchontoglires')

#below this line the API returns a 500 server error:
dendropy_tree = c.taxonomy.dendropy_tree(root='Boreoeutheria')
dendropy_tree = c.taxonomy.dendropy_tree(root='Eutheria')
dendropy_tree = c.taxonomy.dendropy_tree(root='Theria')
dendropy_tree = c.taxonomy.dendropy_tree(root='Amniota')
```
error:
```
Traceback (most recent call last):

  File "<ipython-input-60-6c7b6d8ed68f>", line 1, in <module>
    dendropy_tree = c.taxonomy.dendropy_tree(root='Boreoeutheria')

  File "/usr/local/lib/python3.7/site-packages/omadb/OMARestAPI.py", line 1238, in dendropy_tree
    struct = self.read(root)

  File "/usr/local/lib/python3.7/site-packages/omadb/OMARestAPI.py", line 1186, in read
    (format is not 'dictionary')))

  File "/usr/local/lib/python3.7/site-packages/omadb/OMARestAPI.py", line 456, in _request
    raise ClientException(response_status)

ClientException: 500 Server Error: Internal Server Error 
```

Also, the same problem arises when interacting with the API through the website at this link(https://omabrowser.org/api/docs). E.g. https://omabrowser.org/api/taxonomy/Homininae/ works, but https://omabrowser.org/api/taxonomy/Amniota/ returns the 500 server error.

**Comment by alpae** [comment]
This has been fixed in the latest omabrowser release. thanks for reporting
